In [19]:
from sklearn import datasets
import numpy as np
import pandas as pd
import statistics as st
from sklearn.preprocessing import MinMaxScaler

In [2]:
boston = datasets.load_boston()

In [3]:
X= pd.DataFrame(data=boston.data, columns = boston['feature_names'])

In [112]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [4]:
Y=pd.DataFrame(boston.target)

# low_variability

In [7]:
#Funcion que calcula el rango intercuartilico: 
def iqr(x):
  return np.subtract(*np.percentile(x, [75, 25]))

In [18]:
X.apply(iqr)

CRIM         3.595038
ZN          12.500000
INDUS       12.910000
CHAS         0.000000
NOX          0.175000
RM           0.738000
AGE         49.050000
DIS          3.088250
RAD         20.000000
TAX        387.000000
PTRATIO      2.800000
B           20.847500
LSTAT       10.005000
dtype: float64

In [17]:
st.mean( X.apply(iqr) )

40.20836826923077

In [24]:
X
scaler = MinMaxScaler() 
DF = scaler.fit_transform(X)

In [27]:
X.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

In [28]:
DF = pd.DataFrame(data= DF, columns= X.columns )

In [29]:
DF

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.000000,0.18,0.067815,0.0,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,0.089680
1,0.000236,0.00,0.242302,0.0,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,0.204470
2,0.000236,0.00,0.242302,0.0,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,0.063466
3,0.000293,0.00,0.063050,0.0,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,0.033389
4,0.000705,0.00,0.063050,0.0,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,0.099338
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000633,0.00,0.420455,0.0,0.386831,0.580954,0.681771,0.122671,0.000000,0.164122,0.893617,0.987619,0.219095
502,0.000438,0.00,0.420455,0.0,0.386831,0.490324,0.760041,0.105293,0.000000,0.164122,0.893617,1.000000,0.202815
503,0.000612,0.00,0.420455,0.0,0.386831,0.654340,0.907312,0.094381,0.000000,0.164122,0.893617,1.000000,0.107892
504,0.001161,0.00,0.420455,0.0,0.386831,0.619467,0.889804,0.114514,0.000000,0.164122,0.893617,0.991301,0.131071
505,0.000462,0.00,0.420455,0.0,0.386831,0.473079,0.802266,0.125072,0.000000,0.164122,0.893617,1.000000,0.169702

In [30]:
def low_variability(df,treshold):
    '''
    treshold = float entre 0 y 1 
    FunciÃ³n que descarta las variables con baja variabilidad intercuartilica, dado un treshold
    recibe un data frame y un treshold 
    devuelve las variables que tienen un rango intercuartilico superior a un porcentaje/treshold del rango intercuartilico global y la lista de variables eliminadas
    '''
    #La media de los rangos intercuartilicos del data frame
    DF=df.copy()
    drop_this=[]
    
    feature_matriz= []
    
    #Faltaria estandarizar las variables. 
    scaler = MinMaxScaler() 
    DF = scaler.fit_transform(DF) 
    DF = pd.DataFrame(data= DF, columns= df.columns )
    
    global_iqr=st.mean(DF.apply(iqr))
    treshold = treshold * global_iqr
    
    for i in range(DF.shape[1]):
        iqr_column = iqr(DF.iloc[:,i])
        if iqr_column < treshold:
            drop_this.append(DF.columns[i])
        
    print('columns dropped: ', drop_this)
    DF.drop(columns= drop_this,inplace=True)
            
            
    return DF

In [35]:
low_variability(X,0.4)

columns dropped:  ['CRIM', 'ZN', 'CHAS', 'B']

,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,LSTAT
0,0.067815,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,0.089680
1,0.242302,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,0.204470
2,0.242302,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.063466
3,0.063050,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.033389
4,0.063050,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,0.099338
...,...,...,...,...,...,...,...,...,...
501,0.420455,0.386831,0.580954,0.681771,0.122671,0.000000,0.164122,0.893617,0.219095
502,0.420455,0.386831,0.490324,0.760041,0.105293,0.000000,0.164122,0.893617,0.202815
503,0.420455,0.386831,0.654340,0.907312,0.094381,0.000000,0.164122,0.893617,0.107892
504,0.420455,0.386831,0.619467,0.889804,0.114514,0.000000,0.164122,0.893617,0.131071
505,0.420455,0.386831,0.473079,0.802266,0.125072,0.000000,0.164122,0.893617,0.169702